service: vch-soc

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.12
  stage: ${file(${opt:env}.yml):stage}
  region: ${file(${opt:env}.yml):region}
  profile: ${file(${opt:env}.yml):awsProfile}

custom:
  connectInstanceId: ${file(${opt:env}.yml):connect.instanceId}
  tablePrefix: ${file(${opt:env}.yml):dynamodb.tablePrefix}

functions:
  processInboundCall:
    handler: lambdas/handler.main
    environment:
      CONNECT_INSTANCE_ID: ${self:custom.connectInstanceId}
      TABLE_PREFIX: ${self:custom.tablePrefix}

resources:
  Resources:
    <<: ${file(dynamodb/tables.yml)}
    <<: ${file(connect/contact-flows.yml)}
