service: VCH-SOC

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.12
  stage: ${file(${opt:stage}.yml):stage}
  region: ${file(${opt:stage}.yml):region}
  profile: ${file(${opt:stage}.yml):awsProfile}

custom:
  connectInstanceId: ${file(${opt:stage}.yml):connect.instanceId}
  tablePrefix: ${file(${opt:stage}.yml):dynamodb.tablePrefix}

functions:
  processInboundCall:
    handler: lambdas/handler.main
    environment:
      CONNECT_INSTANCE_ID: ${self:custom.connectInstanceId}
      TABLE_PREFIX: ${self:custom.tablePrefix}
  
  Testoutboundcall:
    handler: lambdas/handler.main
    environment:
      CONNECT_INSTANCE_ID: ${self:custom.connectInstanceId}
      TABLE_PREFIX: ${self:custom.tablePrefix}

resources: ${file(resources.yml)}
